var contactFormID = "contact-form-1",
    contactForm = document.getElementById(contactFormID);
if (contactForm)
    var simple_form_contact = new SimpleForms("#" + contactFormID, {
        action: "assets/vendor/simple-forms/sendmail.php",
        lang: "en",
        theme: "faded-dark",
        style: "none",
        ajaxSubmit: !0,
        validate: !0,
        validateOnKeyup: !0,
        browserValidation: !1,
        tooltips: !0,
        showErrors: !0,
        responseOverlay: !1,
        focusErrorFields: !0,
        debug: !0,
        hideFormAfterSubmit: !1,
        customSuccessMessage: "",
        formCSS: "",
        files: {
            enabled: !1,
            extensions: "jpg jpeg svg png",
            min: 0,
            max: 10,
            maxFileSize: 24,
            filesUploadHandler: "simple-forms/files-upload-handler.php",
        },
        redirect: { enabled: !1, url: "success.html", timeout: 3 },
        captcha: {
            enabled: !0,
            type: "recaptcha-v3",
            siteKey: "CHANGEME",
            theme: "dark",
        },
        accessibility: { escapeReset: !0, tabHighlight: !1 },
        consent: !1,
        validator: {
            rules: {
                ".validate-name": { required: !0, min: 2, max: 30, name: !0 },
                ".validate-email": { required: !0, min: 8, email: !0 },
            },
        },
    });
var subscribeFormID = "sk__subscribe-form-1",
    subscribeForm = document.getElementById(subscribeFormID);
if (subscribeForm)
    var simple_form_subscribe = new SimpleForms("#" + subscribeFormID, {
        action: "assets/vendor/simple-forms/sendmail.php",
        lang: "en",
        theme: "faded-dark",
        style: "none",
        ajaxSubmit: !0,
        validate: !0,
        validateOnKeyup: !0,
        browserValidation: !1,
        tooltips: !0,
        showErrors: !0,
        responseOverlay: !1,
        focusErrorFields: !0,
        debug: !0,
        hideFormAfterSubmit: !1,
        customSuccessMessage: "",
        formCSS: "",
        files: {
            enabled: !1,
            extensions: "jpg jpeg svg png",
            min: 0,
            max: 10,
            maxFileSize: 24,
            filesUploadHandler: "simple-forms/files-upload-handler.php",
        },
        redirect: { enabled: !1, url: "success.html", timeout: 3 },
        captcha: {
            enabled: !0,
            type: "recaptcha-v3",
            siteKey: "CHANGEME",
            theme: "dark",
        },
        accessibility: { escapeReset: !0, tabHighlight: !1 },
        consent: !1,
        validator: {
            rules: {
                ".validate-name": { required: !0, min: 2, max: 30, name: !0 },
                ".validate-email": { required: !0, min: 8, email: !0 },
            },
        },
    });
